### ISSUE TITLE
The readme should warn about this library being unsuitable for standards-compliant base encoding

### ISSUE THREAD

**Issue by aidanhs** [OrKoN/base-x-rs#13]
Per https://github.com/cryptocoinjs/base-x

> WARNING: This module is NOT RFC3548 compliant, it cannot be used for base16 (hex), base32, or base64 encoding in a standards compliant manner.

This is because standards-compliant base64 aligns the start of processing with the *start* of the data (hence implicitly padding the bottom with zeroes), whereas base-x aligns with the *end* (therefore padding the top) - it will work *sometimes*, if the number of bits in the data is divisible by 6 (for base64) as there are no bits to pad. I found https://www.lucidchart.com/techblog/2017/10/23/base64-encoding-a-visual-explanation/ useful to help my understanding)

(as it happens, I *think* it might be ok for base16 because bytes are always divisible into 4 bits, but 5 bits with base32 surely has the same problem)

Concretely, encoding 'A' with a standards compliant base64 encoder results in `QQ`, but results in `BB` with base-x.

**Comment by OrKoN** [comment]
Added an explicit warning (copied from the original repo). Thanks
