### ISSUE TITLE
Use a slice of chars instead of a slice of bytes as the alphabet

### ISSUE THREAD

**Issue by TheZalli** [OrKoN/base-x-rs#4]
Using an array of bytes as the alphabet is fine if all we are using is ASCII characters that are byte each, but however Rust strings are UTF-8 strings by default, meaning the characters in strings can be multiple bytes (`char` type is 4 bytes).

[Also, not all Unicode characters (unicode codepoints) can be represented by a `char`, that is just a 'unicode scalar value'.](https://doc.rust-lang.org/std/primitive.char.html)

I might do a pull request on this later.

**Comment by maciejhirsz** [comment]
Hey!

Do you actually have a use case where a non-ASCII alphabet would be desired? From technical pov using `char` for base can introduce a considerable decoding performance hit, as you end up having to use a hashmap for each alphabet, where for ASCII a regular 256-byte stack array suffices.

If this is really desirable, I'd consider some form of specialization for ASCII and non-ASCII alphabets to work around this issue, without hurting the performance for most common alphabets.

Sidenote: A thing to consider is that `char` also isn't really what a human would consider a character, example of this would be emojis and various asian alphabets that use grapheme clusters (spanning multiple unicode scalars).

**Comment by TheZalli** [comment]
I don't have a use case personally, but being strictly ASCII without specifying it seems slightly silly when the whole language has UTF-8 support.

Specialization into different alphabet types (byte, `char`, `str`/unicode codepoint) sounds like a good idea, so that you can choose between performance and unicode support.

**Comment by maciejhirsz** [comment]
I got an idea how to do it and incorporate it in #5. Can make it so `&[u8]` will be treated as an ASCII alphabet, while `&str` will be treated as a unicode alphabet by default, with an option to build pretty much any definition of a custom alphabet using any kind of structure for byte/char -> index lookup, be it plain array, hashmap, vecmap, btreemap or anything else.

Does that sound ok?

**Comment by TheZalli** [comment]
That sounds like a good thing to do, although if we use `&str` as an alphabet we can't get the full codepoints easily, but if we wanted that we could use a custom structure implementing a trait anyway.

**Comment by maciejhirsz** [comment]
This should be now resolved with #5, see [this test](https://github.com/maciejhirsz/base-x-rs/blob/9dd116cf8f527473a04f99a07213612e7db18a4f/src/lib.rs#L168-L178).

@mrZalli it should be pretty easy to `impl<'a> Alphabet for &'a [char]` now that this is in place, where you don't have to abuse the `Chars` iterator to get the nth char from the alphabet (as it does currently for `&str`).
